name: Build EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: >
        pyinstaller 
        --onefile 
        --noconsole 
        --clean 
        --name "MiyaGantt-v2.2.0" 
        --icon icon.ico 
        --add-data "README.md;." 
        --add-data "icon.ico;." 
        --collect-all PySide6 
        --hidden-import jpholiday 
        app.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MiyaGantt-v2.2.0
        path: dist/MiyaGantt-v2.2.0.exe